"use client";
import { useRef } from "react";
import type { QuizGraph } from "@/lib/quiz/contracts";
import { targets } from "@/lib/quiz/graph";
import { nodeLabels } from "@/lib/quiz/editor-state";

export function QuizCanvas({ graph, selectedId, onSelect, onChange }: { graph: QuizGraph; selectedId: string | null; onSelect(id: string): void; onChange(g: QuizGraph): void }) {
  const drag = useRef<{ id: string; startX: number; startY: number; x: number; y: number } | null>(null);
  const width = Math.max(640, ...graph.nodes.map(n => n.x + 280));
  const height = Math.max(480, ...graph.nodes.map(n => n.y + 160));
  const move = (id: string, x: number, y: number) => onChange({ ...graph, nodes: graph.nodes.map(n => n.id === id ? { ...n, x: Math.max(0, Math.min(5000, Math.round(x))), y: Math.max(0, Math.min(5000, Math.round(y))) } : n) });
  return <div className="max-w-full overflow-auto border border-border bg-background" style={{ height: 560 }} aria-label="Plansza ścieżki"><div className="relative" style={{ width, height, backgroundImage: "radial-gradient(var(--color-border) 1px, transparent 1px)", backgroundSize: "20px 20px" }}><svg className="pointer-events-none absolute inset-0" width={width} height={height} aria-label="Połączenia kroków"><defs><marker id="quiz-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="var(--color-accent-ink)" /></marker></defs>{graph.nodes.flatMap(n => targets(n).map((id, i) => { const target = graph.nodes.find(t => t.id === id); if (!target) return null; const x = n.x + 115, y = n.y + 112, tx = target.x + 115, ty = target.y; return <path key={`${n.id}-${i}`} data-source={n.id} data-target={id} d={`M${x},${y} C${x},${y + 45} ${tx},${ty - 45} ${tx},${ty - 5}`} fill="none" stroke="var(--color-accent-ink)" strokeWidth="2" markerEnd="url(#quiz-arrow)" />; }))}</svg>{graph.nodes.map(n => <div key={n.id} className={`absolute w-[230px] border-2 bg-surface shadow-sm ${selectedId === n.id ? "border-foreground" : "border-border"}`} style={{ left: n.x, top: n.y }}><button type="button" aria-label={`Przesuń krok: ${n.label}`} className="flex min-h-8 w-full touch-none items-center justify-between bg-surface-subtle px-3 text-xs text-muted" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); drag.current = { id: n.id, startX: e.clientX, startY: e.clientY, x: n.x, y: n.y }; onSelect(n.id); }} onPointerMove={e => { const d = drag.current; if (d?.id === n.id) move(n.id, d.x + e.clientX - d.startX, d.y + e.clientY - d.startY); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }} onKeyDown={e => { if (["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(e.key)) { e.preventDefault(); move(n.id, n.x + (e.key === "ArrowRight" ? 20 : e.key === "ArrowLeft" ? -20 : 0), n.y + (e.key === "ArrowDown" ? 20 : e.key === "ArrowUp" ? -20 : 0)); } }}><span>{n.type === "start" ? n.trigger === "dm" ? "Start · słowo w DM" : "Start · komentarz" : nodeLabels[n.type]}</span><span aria-hidden>⠿</span></button><button type="button" className="min-h-[76px] w-full px-3 py-3 text-left text-sm font-semibold leading-relaxed" aria-pressed={selectedId === n.id} onClick={() => onSelect(n.id)}>{n.label || "Bez nazwy"}</button></div>)}</div></div>;
}
