"use client";
import type { QuizGraph, QuizNode } from "@/lib/quiz/contracts";
import { Field, FieldsForm, ListInput } from "./fields";
import { QualificationForm } from "./qualification-form";

export function NodeForm({ node: n, graph, onChange }: { node: QuizNode; graph: QuizGraph; onChange(n: QuizNode): void }) {
  const next = (value: string, set: (id: string) => void, label = "Połącz z krokiem") => <Field label={label}><select className="app-field" value={value} onChange={e => set(e.target.value)}><option value="">Wybierz krok</option>{graph.nodes.filter(t => t.id !== n.id && t.type !== "start").map(t => <option key={t.id} value={t.id}>{t.label || t.id}</option>)}</select></Field>;
  return <div className="space-y-5"><Field label="Nazwa kroku"><input className="app-field" maxLength={100} value={n.label} onChange={e => onChange({ ...n, label: e.target.value })} /></Field>{"text" in n && <Field label="Treść wiadomości"><textarea className="app-field min-h-32" maxLength={n.type === "message" && !n.material ? 1000 : 640} value={n.text} onChange={e => onChange({ ...n, text: e.target.value })} /></Field>}
    {n.type === "start" && <><Field label="Hasło w komentarzu"><input className="app-field" maxLength={80} value={n.keyword} onChange={e => onChange({ ...n, keyword: e.target.value })} /></Field><Field label="Przycisk rozpoczynający quiz"><input className="app-field" maxLength={20} value={n.cta} onChange={e => onChange({ ...n, cta: e.target.value })} /></Field><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={n.allPosts} onChange={e => onChange({ ...n, allPosts: e.target.checked })} />Wszystkie posty tego konta</label>{!n.allPosts && <Field label="Identyfikatory postów (oddzielone przecinkami)"><ListInput value={n.postIds} onChange={postIds => onChange({ ...n, postIds })} /></Field>}<p className="text-sm leading-relaxed text-muted">Komentarz wyśle tylko zaproszenie. Quiz rozpocznie się po kliknięciu przycisku.</p></>}
    {n.type === "message" && <><label className="flex gap-3 text-sm"><input type="checkbox" checked={!!n.material} onChange={e => onChange({ ...n, material: e.target.checked ? { name: "Otwórz materiał", url: "" } : undefined })} />Dodaj przycisk z materiałem</label>{n.material && <><Field label="Nazwa przycisku materiału"><input className="app-field" maxLength={20} value={n.material.name} onChange={e => onChange({ ...n, material: { ...n.material!, name: e.target.value } })} /></Field><Field label="Adres materiału HTTPS"><input className="app-field" type="url" value={n.material.url} onChange={e => onChange({ ...n, material: { ...n.material!, url: e.target.value } })} /></Field></>}</>}
    {n.type === "question" && <><Field label="Rodzaj odpowiedzi"><select className="app-field" value={n.input} onChange={e => onChange({ ...n, input: e.target.value as typeof n.input, choices: e.target.value === "choice" ? n.choices.length ? n.choices : [{ id: `${n.id}-a1`, label: "Tak", value: "tak", next: "" }] : [] })}><option value="choice">Wybór przyciskiem</option><option value="text">Wpisany tekst</option><option value="email">Adres e-mail</option></select></Field><Field label="Zapisz odpowiedź w polu"><input className="app-field" maxLength={80} value={n.field} onChange={e => onChange({ ...n, field: e.target.value })} /></Field><label className="flex gap-3 text-sm"><input type="checkbox" checked={n.required} onChange={e => onChange({ ...n, required: e.target.checked })} />Odpowiedź wymagana</label>{!n.required && <p className="text-sm text-muted">Przycisk „Pomiń” zajmuje jedno z trzech miejsc.</p>}{n.input === "choice" && <div className="space-y-4">{n.choices.map((c, i) => <div key={c.id} className="space-y-3 border border-border p-3"><Field label={`Przycisk odpowiedzi ${i + 1}`}><input className="app-field" maxLength={20} value={c.label} onChange={e => onChange({ ...n, choices: n.choices.map(t => t.id === c.id ? { ...t, label: e.target.value } : t) })} /></Field><Field label={`Zapisywana odpowiedź ${i + 1}`}><input className="app-field" maxLength={1000} value={c.value} onChange={e => onChange({ ...n, choices: n.choices.map(t => t.id === c.id ? { ...t, value: e.target.value } : t) })} /></Field>{next(c.next, id => onChange({ ...n, choices: n.choices.map(t => t.id === c.id ? { ...t, next: id } : t) }), `Po odpowiedzi ${i + 1}`)}<button type="button" className="text-sm text-error underline" onClick={() => onChange({ ...n, choices: n.choices.filter(t => t.id !== c.id) })}>Usuń odpowiedź {i + 1}</button></div>)}<button type="button" className="app-button app-button-secondary" disabled={n.choices.length >= (n.required ? 3 : 2)} onClick={() => onChange({ ...n, choices: [...n.choices, { id: `a-${crypto.randomUUID()}`, label: "Nowa odpowiedź", value: "", next: "" }] })}>Dodaj odpowiedź</button></div>}{n.input === "email" && <p className="text-sm leading-relaxed text-muted">Sprawdzamy format adresu. Podanie e-maila nie potwierdza jego własności ani zgody na newsletter.</p>}</>}
    {n.type === "condition" && <><QualificationForm graph={graph} value={n.when} onChange={when => onChange({ ...n, when })} />{next(n.yes, yes => onChange({ ...n, yes }), "Warunek spełniony → krok")}{next(n.no, no => onChange({ ...n, no }), "Warunek niespełniony → krok")}</>}
    {n.type === "action" && <><Field label="Dodaj tagi (oddzielone przecinkami)"><ListInput value={n.addTags} onChange={addTags => onChange({ ...n, addTags })} /></Field><Field label="Usuń tagi (oddzielone przecinkami)"><ListInput value={n.removeTags} onChange={removeTags => onChange({ ...n, removeTags })} /></Field><Field label="Zainteresowanie pomocą / ofertą"><select className="app-field" value={n.interest === undefined ? "keep" : String(n.interest)} onChange={e => onChange({ ...n, interest: e.target.value === "keep" ? undefined : e.target.value === "true" })}><option value="keep">Pozostaw obecną wartość</option><option value="true">Tak — zadeklarowane zainteresowanie</option><option value="false">Nie</option></select></Field><FieldsForm value={n.setFields} onChange={setFields => onChange({ ...n, setFields })} /></>}
    {n.type === "end" && <Field label="Zakończenie ścieżki"><select className="app-field" value={n.outcome} onChange={e => onChange({ ...n, outcome: e.target.value as typeof n.outcome })}><option value="completed">Zakończ quiz</option><option value="human">Przekaż rozmowę administratorowi</option></select></Field>}
    {"next" in n && !(n.type === "question" && n.input === "choice" && n.required) && next(n.next, id => onChange({ ...n, next: id }), n.type === "question" && n.input === "choice" ? "Po pominięciu → krok" : "Połącz z krokiem")}
  </div>;
}
