"use client";
import type { Criterion, QuizGraph, RuleGroup } from "@/lib/quiz/contracts";
import { Field, ValueInput } from "./fields";

const labels: Record<Criterion["kind"], string> = { email: "Poprawny e-mail", interest: "Zainteresowanie pomocą / ofertą", tag: "Tag kontaktu", answer: "Odpowiedź na pytanie", field: "Wartość pola", completed: "Ukończony krok" };
export function QualificationForm({ value, graph, onChange }: { value: RuleGroup; graph: QuizGraph; onChange(v: RuleGroup): void }) {
  const replace = (i: number, rule: Criterion) => onChange({ ...value, rules: value.rules.map((r, j) => i === j ? rule : r) });
  return <div className="space-y-4"><Field label="Sposób łączenia warunków"><select className="app-field" value={value.mode} onChange={e => onChange({ ...value, mode: e.target.value as RuleGroup["mode"] })}><option value="any">Dowolny warunek (LUB)</option><option value="all">Wszystkie warunki (I)</option></select></Field>{value.rules.map((r, i) => <div key={i} className="space-y-3 rounded border border-border p-3"><Field label={`Warunek ${i + 1}`}><select className="app-field" value={r.kind} onChange={e => { const kind = e.target.value as Criterion["kind"]; replace(i, kind === "tag" ? { kind, value: "" } : kind === "field" ? { kind, key: "", value: "" } : kind === "answer" ? { kind, nodeId: "", value: "" } : kind === "completed" ? { kind, nodeId: "" } : { kind }); }}>{Object.entries(labels).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></Field>{(r.kind === "answer" || r.kind === "completed") && <Field label={`Krok warunku ${i + 1}`}><select className="app-field" value={r.nodeId} onChange={e => replace(i, { ...r, nodeId: e.target.value })}><option value="">Wybierz krok</option>{graph.nodes.filter(n => r.kind !== "answer" || n.type === "question").map(n => <option key={n.id} value={n.id}>{n.label || n.id}</option>)}</select></Field>}{r.kind === "tag" && <Field label="Wymagany tag"><input className="app-field" maxLength={80} value={r.value} onChange={e => replace(i, { ...r, value: e.target.value })} /></Field>}{r.kind === "field" && <Field label="Pole warunku"><select className="app-field" value={r.key} onChange={e => replace(i, { ...r, key: e.target.value })}><option value="">Wybierz pole</option>{[...new Set(graph.nodes.flatMap(n => n.type === "question" ? [n.field] : n.type === "action" ? Object.keys(n.setFields) : []))].filter(Boolean).map(k => <option key={k}>{k}</option>)}</select></Field>}{(r.kind === "field" || r.kind === "answer") && <ValueInput value={r.value} label={`Oczekiwana wartość ${i + 1}`} onChange={v => replace(i, { ...r, value: v })} />}<button type="button" className="text-sm text-error underline" onClick={() => onChange({ ...value, rules: value.rules.filter((_, j) => j !== i) })}>Usuń warunek {i + 1}</button></div>)}<button type="button" className="app-button app-button-secondary" disabled={value.rules.length >= 10} onClick={() => onChange({ ...value, rules: [...value.rules, { kind: "email" }] })}>Dodaj warunek</button></div>;
}
